vich_uploader:
    db_driver: orm

    mappings:
        offre_image:
            uri_prefix: /images/offres
            upload_destination: '%kernel.project_dir%/public/images/offres'
        cv:
            uri_prefix: /images/cv
            upload_destination: '%kernel.project_dir%/public/images/cv'
