#index:
#    path: /home
#    controller: App\Controller\DefaultController::index

captcha_routing:
     resource: "@CaptchaBundle/Resources/config/routing.yml"
login:
     path: /login
     controller: App\Controller\SecurityController::login
     methods: POST